#ifndef EKAMDASHBOARD_GLOBAL_H
#define EKAMDASHBOARD_GLOBAL_H

#include <QtGlobal>

#if defined(EKAMDASHBOARD_LIBRARY)
#  define EKAMDASHBOARDSHARED_EXPORT Q_DECL_EXPORT
#else
#  define EKAMDASHBOARDSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // EKAMDASHBOARD_GLOBAL_H

